### PR TITLE
Add a .env_sample file

### PR DESCRIPTION
**Pull request by thepriefy**
issue #55

### CODE REVIEW

**Comment by thepriefy** [comment]
@fishnux I'm done! Could you please check whether there are any other problems that occur?

**Comment by mbernier** [comment]
@fishnux thanks for the advice and the help on this ticket, that was a great reason to not have export. I will see what I can do to make sure we don't have that in our other repos either.

**Comment by thinkingserious** [comment]
Hello @thepriefy,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mbernier** [comment]
@fishnux how are you using a key/value file locally? I looked up a couple options, but it seems like they all kind of suck - was hoping for a one-line bash command to say "use all these vars as exports, even though the word export isn't available in the file"

**Comment by thepriefy** [comment]
@mbernier do I have to remove 'export' in all .sample_env files?
(some of my changes in other repo have already merged to master branch so I will go back and fix them.)

**Comment by fishnux** [comment]
I usually use https://github.com/vlucas/phpdotenv to load .env files in PHP projects. I wasn't aware that removing the export keyword would produce slightly different results on Bash. 
This command seems to work good:
```
eval $(cat .env | sed 's/^/export /')
````
Perhaps we could also setup an alias for that command, here's an example:
```
alias loadenv="eval $(cat .env | sed 's/^/export /')"
```
(That would go in .bashrc, or .zshrc)

**Pull request merged**
