### PR TITLE
Add unittest to check that specific files exist in repo

### LINKED ISSUE #66: Add unittest to check for specific repo files
This repo should have the following list of files included:
- ./Docker or docker/Docker
- ./docker-compose.yml or ./docker/docker-compose.yml
- ./.env_sample
- ./.gitignore
- ./.travis.yml
- ./.codeclimate.yml
- ./CHANGELOG.md
- ./CODE_OF_CONDUCT.md
- ./CONTRIBUTING.md
- ./.github/ISSUE_TEMPLATE
- ./LICENSE.md
- ./.github/PULL_REQUEST_TEMPLATE
- ./README.md
- ./TROUBLESHOOTING.md
- ./USAGE.md
- ./USE_CASES.md

This PR is only asking for tests of the existence of these files, if the files do not exist when you run the tests - do not worry about the tests not passing. We will identify this and create a new PR for the issue.
Thank you!

### PR DESCRIPTION
**Pull request by bertuss**
### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:

Add unit test to ensure specific file exist in the repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-php?pullRequest=69) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-php?pullRequest=69) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-php?pullRequest=69) it.</sub>

**Comment by mbernier** [comment]
I just checked the Travis logs and this is what I found - do you know why this might be happening? 
```
PHPUnit 3.7.38 by Sebastian Bergmann.
Configuration read from /home/travis/build/sendgrid/smtpapi-php/test/phpunit.xml.dist
Time: 12 ms, Memory: 2.00MB
No tests executed!
Generating code coverage report in Clover XML format ... done
```
Specifically, the `No tests executed!` part. I am not sure why the tests might not be running. 
cc @thinkingserious for support

**Comment by bertuss** [comment]
Lol, I forgot to update `test/phpunit.xml.dist` to include the new test file. Will do in a bit.

**Comment by mbernier** [comment]
@bertuss can you please make that last change, we would like to merge this into the repo!

**Comment by mbernier** [comment]
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/30min) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Comment by mbernier** [comment]
Beautiful! Thanks for the quick turn around. Please let me know if you are available to chat on a google hangout or skype!!

**Comment by thinkingserious** [comment]
Hello @bertuss,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
