### PR TITLE
Add a USAGE.md file

### PR DESCRIPTION
**Pull request by pxgamer**
Added a [USAGE.md] file as per #41.

It says basic in the issue, and I'm sure more can be added over time.

Anything that I should change or update, let me know.

[USAGE.md]: https://github.com/pxgamer/smtpapi-php/blob/feature/usage_file/USAGE.md

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-php?pullRequest=49) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-php?pullRequest=49) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-php?pullRequest=49) it.</sub>

**Comment by mbernier** [comment]
This is awesome. Thank you!!

**Comment by thinkingserious** [comment]
Hello @pxgamer,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by pxgamer** [comment]
@thinkingserious I've filled it in. 👍 Just wanted to check it's all fine.

**Pull request merged**
